name: Testing

on:
  push:
    branches:
      - main
  pull_request:
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: Run cargo clippy
        run: cargo clippy --all-targets -- --deny warnings
  clippy-python:
    name: Clippy-Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: Run cargo clippy
        run: cargo clippy --all-targets -F python -- --deny warnings
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
  check-python:
    name: Check-Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: Run cargo fmt
        run: cargo check --all-targets -F python
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: Run cargo test
        run: cargo test --locked
